# https://taskfile.dev

version: '2'

env:
  DOCKER_IMAGE: wikipedia_pageviews
  ENV: '{{default "minikube" .ENV}}'
  DOCKER_REGISTRY: '{{default "mrmuggymuggy" .DOCKER_REGISTRY}}'
  NAMESPACE: '{{default "default" .NAMESPACE}}'
  VERSION: 0.1.0

vars:
  KUBE_CONTEXT: '{{default "minikube" .KUBE_CONTEXT}}'
  HELM_CHART_NAME: wikipedia-pageviews-helm
  DEFAULT_SERVICES: |-
    wikipedia-pageviews

includes:
  dags: ./airflow-dags

tasks:

  lint:
    cmds:
      - pylint --exit-zero jobs

  format:
    cmds:
      - pip install pre-commit
      - pre-commit install
      - pre-commit run --all-files

  docker.build:
    summary: |
      Build docker image of spark ETL job
    cmds:
      - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$VERSION .

  jupyter:
    summary: |
      Local development with jupyter-notebook, fast feedback MVP
    cmds:
      #jupyter with latest spark
      - docker-compose up --abort-on-container-exit wikipedia_pageviews_jupyter

  local.run:
    summary: |
      Run the app locally with docker-compose
    cmds:
      - docker-compose up --abort-on-container-exit --build wikipedia_pageviews

  local.daterange.run:
    summary: |
      Run the app locally for a date range with docker-compose
      eg. START_DATE=2020-01-22T02 END_DATE=2020-01-22T03 task local.daterange.run
    cmds:
      - |
        #docker-compose build wikipedia_pageviews
        start=$(date -d"$START_DATE" +"%Y-%m-%dT%H")
        end=$(date -d"$END_DATE" +"%Y-%m-%dT%H")
        while [[ $start < $end ]]
        do
            echo execute spark job at $start time
            docker-compose run -e EXECUTION_DATETIME=$start wikipedia_pageviews
            start=$(date -d"$start + 1 hour" +"%Y-%m-%dT%H")
        done;
    env:
      START_DATE:
        '{{default "2020-01-22T08:00" .START_DATE}}'
      END_DATE:
        '{{default "2020-01-22T10:00" .END_DATE}}'

  unit-tests:
    summary: |
      Run the unit-tests locally with docker-compose
    cmds:
      - docker-compose up --abort-on-container-exit --build wikipedia_pageviews_tests

  airflow.deploy:
    deps: [set.k8s.context]
    cmds:
      #my helm chart repo
      - helm repo add mrmuggymuggy https://mrmuggymuggy.github.io/helm-charts/
      - helm repo update
      - helm install airflow mrmuggymuggy/airflow --wait --timeout 600s

  airflow.undeploy:
    deps: [set.k8s.context]
    cmds:
      - helm uninstall airflow

  start.minikube:
    cmds:
      - if minikube status | grep Running; then echo "minikube running..."; else echo "starting minikube"; minikube start; fi

  set.k8s.context:
    cmds:
      - kubectl config set-context {{.KUBE_CONTEXT}} --namespace=$NAMESPACE
      - kubectl config use-context {{.KUBE_CONTEXT}} --namespace=$NAMESPACE

  default:
    cmds:
      - echo 'executed on {{if ne .KUBE_CONTEXT "minikube"}}remote{{else}}local{{end}}'
    silent: true
